# Generated by Django 2.0.4 on 2018-05-08 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptinfo',
            options={'verbose_name': '部门信息表', 'verbose_name_plural': '部门信息表'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='power_level',
            field=models.CharField(choices=[('sys_admin', '系统管理员'), ('head_admin', '总行管理员'), ('branch_admin', '分行管理员')], default='3', max_length=64, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='adminuserprofile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='power_level',
            field=models.CharField(choices=[('branch_assist', '分行协理员'), ('dept_manager', '部门管理员'), ('dept_operator', '部门操作员'), ('auditor', '审计检查员')], default='DeptOperator', max_length=64, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='branchuserprofile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.BranchUser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='headuser',
            name='power_level',
            field=models.CharField(choices=[('team_manager', '团队管理员'), ('guard_judge', '值班审核员'), ('claims_man', '事件调查员'), ('guard_manager', '值班管理员'), ('temporary', '临时操作员'), ('auditor', '审计检查员')], default='HeadAdmin', max_length=64, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='headuserprofile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.HeadUser', verbose_name='用户'),
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_user',
        ),
        migrations.AlterModelTable(
            name='adminuserprofile',
            table='admin_user_profile',
        ),
        migrations.AlterModelTable(
            name='branchuser',
            table='branch_user',
        ),
        migrations.AlterModelTable(
            name='branchuserprofile',
            table='branch_user_profile',
        ),
        migrations.AlterModelTable(
            name='deptinfo',
            table='team_info',
        ),
        migrations.AlterModelTable(
            name='headuser',
            table='head_user',
        ),
        migrations.AlterModelTable(
            name='headuserprofile',
            table='head_user_profile',
        ),
    ]
