# Generated by Django 2.0.4 on 2018-05-15 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskClosure',
            fields=[
                ('article_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique_for_date='publish', verbose_name='简称')),
                ('body', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布')], default='draft', max_length=10, verbose_name='状态')),
                ('rank', models.CharField(choices=[('1', '特危'), ('2', '高危')], default='2', max_length=10, verbose_name='风险等级')),
                ('author_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_closure_author', to='account.HeadUser', verbose_name='作者')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '风险提示',
                'verbose_name_plural': '风险提示',
                'db_table': 'risk_closure',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('comment_id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='评论编号')),
                ('body', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='评论正文')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('article_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment_article', to='centre.RiskClosure', verbose_name='文章编号')),
                ('comment_user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment_user', to='account.HeadUser', verbose_name='评论人员')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'user_comments',
            },
        ),
    ]
