# Generated by Django 2.0.4 on 2018-05-08 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskClosure',
            fields=[
                ('article_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique_for_date='publish', verbose_name='简称')),
                ('body', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('p_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布')], default='draft', max_length=10, verbose_name='状态')),
                ('rank', models.CharField(choices=[('1', '特危'), ('2', '高危')], default='2', max_length=10, verbose_name='风险等级')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Article', to='account.HeadUser', verbose_name='作者')),
            ],
            options={
                'verbose_name': '风险提示',
                'verbose_name_plural': '风险提示',
                'db_table': 'risk_closure',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
