# Generated by Django 2.0.4 on 2018-05-08 14:14

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('account', '0001_initial'),
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='评论正文')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('active', models.BooleanField(default=True, verbose_name='用户状态')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'user_comments',
            },
        ),
        migrations.AddField(
            model_name='riskclosure',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='riskclosure',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='account.HeadUser', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='article_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_article_id', to='centre.RiskClosure', verbose_name='文章编号'),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user_id', to='account.HeadUser', verbose_name='评论人员'),
        ),
    ]
