# Generated by Django 2.0.4 on 2018-05-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180515_1436'),
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='candidate_user_id',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='candidate_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_candidate_user', to='account.HeadUser', verbose_name='被评人'),
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='judge_user_id',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='judge_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_judge_user', to='account.HeadUser', verbose_name='评价人'),
        ),
    ]
