# Generated by Django 2.0.4 on 2018-04-26 02:19

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('institution', models.CharField(choices=[('1', '总行'), ('2', '分行')], default='1', max_length=64, verbose_name='机构')),
                ('organization', models.CharField(db_index=True, default='', max_length=255, verbose_name='单位')),
                ('tel', models.CharField(default='', max_length=255, verbose_name='电话')),
                ('mail', models.EmailField(default='', max_length=255, verbose_name='邮箱')),
                ('start_from', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('end_to', models.DateField(verbose_name='有效期限')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.IntegerField(default=0)),
                ('dept', models.CharField(default='', max_length=255, verbose_name='团队')),
                ('power_level', models.CharField(choices=[('1', '系统管理员'), ('2', '总行管理员'), ('3', '分行管理员')], default='3', max_length=64, verbose_name='权限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='admin_user_set', related_query_name='admin_user', to='auth.Group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='admin_user_set', related_query_name='admin_user', to='auth.Permission', verbose_name='管理员用户权限')),
            ],
            options={
                'verbose_name': '管理员用户表',
                'db_table': 'AdminUser',
            },
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BranchUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('institution', models.CharField(choices=[('1', '总行'), ('2', '分行')], default='1', max_length=64, verbose_name='机构')),
                ('organization', models.CharField(db_index=True, default='', max_length=255, verbose_name='单位')),
                ('tel', models.CharField(default='', max_length=255, verbose_name='电话')),
                ('mail', models.EmailField(default='', max_length=255, verbose_name='邮箱')),
                ('start_from', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('end_to', models.DateField(verbose_name='有效期限')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.IntegerField(default=0)),
                ('dept', models.CharField(default='', max_length=255, verbose_name='部门')),
                ('power_level', models.CharField(choices=[('1', '分行协理员'), ('2', '部门管理员'), ('3', '部门操作员'), ('4', '合规管理员')], default='3', max_length=64, verbose_name='权限')),
                ('groups', models.ManyToManyField(blank=True, help_text='请为用户组分配权限！', related_name='branch_user_set', related_query_name='branch_user', to='auth.Group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='请为用户分配权限！', related_name='branch_user_set', related_query_name='branch_user', to='auth.Permission', verbose_name='分行用户权限')),
            ],
            options={
                'verbose_name': '分行用户表',
                'db_table': 'BranchUser',
            },
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('organization_ch', models.CharField(max_length=255)),
                ('dept_ch', models.CharField(max_length=255)),
                ('mail', models.EmailField(blank=True, max_length=64, null=True)),
                ('ceo', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'TeamInfo',
            },
        ),
        migrations.CreateModel(
            name='HeadUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('institution', models.CharField(choices=[('1', '总行'), ('2', '分行')], default='1', max_length=64, verbose_name='机构')),
                ('organization', models.CharField(db_index=True, default='', max_length=255, verbose_name='单位')),
                ('tel', models.CharField(default='', max_length=255, verbose_name='电话')),
                ('mail', models.EmailField(default='', max_length=255, verbose_name='邮箱')),
                ('start_from', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('end_to', models.DateField(verbose_name='有效期限')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.IntegerField(default=0)),
                ('dept', models.CharField(default='', max_length=255, verbose_name='团队')),
                ('power_level', models.CharField(choices=[('1', '团队管理员'), ('2', '值班审核员'), ('3', '事件调查员'), ('4', '值班管理员'), ('5', '临时操作员'), ('6', '审计检查员')], default='5', max_length=64, verbose_name='权限')),
                ('re_user_id', models.CharField(default='', max_length=64, verbose_name='remedy账号')),
                ('re_password', models.CharField(default='', max_length=64, verbose_name='remedy密码')),
                ('groups', models.ManyToManyField(blank=True, help_text='请为用户组分配权限！', related_name='head_user_set', related_query_name='head_user', to='auth.Group', verbose_name='用户组')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='请为用户分配权限！', related_name='head_user_set', related_query_name='head_user', to='auth.Permission', verbose_name='总行用户权限')),
            ],
            options={
                'verbose_name': '总行用户表',
                'db_table': 'HeadUser',
            },
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deptinfo',
            unique_together={('organization', 'dept')},
        ),
    ]
