# Generated by Django 2.0.4 on 2018-04-26 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180426_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='end_to',
            field=models.DateTimeField(default=datetime.date(2019, 4, 26), verbose_name='有效期限'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='start_from',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='end_to',
            field=models.DateTimeField(default=datetime.date(2019, 4, 26), verbose_name='有效期限'),
        ),
        migrations.AlterField(
            model_name='branchuser',
            name='start_from',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='headuser',
            name='end_to',
            field=models.DateTimeField(default=datetime.date(2019, 4, 26), verbose_name='有效期限'),
        ),
        migrations.AlterField(
            model_name='headuser',
            name='start_from',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
