# Generated by Django 2.0.4 on 2018-04-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180426_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': '管理员用户表', 'verbose_name_plural': '管理员用户表'},
        ),
        migrations.AlterModelOptions(
            name='branchuser',
            options={'verbose_name': '分行用户表', 'verbose_name_plural': '分行用户表'},
        ),
        migrations.AlterModelOptions(
            name='headuser',
            options={'verbose_name': '总行用户表', 'verbose_name_plural': '总行用户表'},
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='branchuser',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='headuser',
            old_name='mail',
            new_name='email',
        ),
    ]
