# Generated by Django 2.0.4 on 2018-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchorganizationinfo',
            name='organization_ch',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='headorganizationinfo',
            name='organization_ch',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='branchdeptinfo',
            name='dept',
            field=models.CharField(max_length=255, verbose_name='部门代号'),
        ),
        migrations.AlterField(
            model_name='branchdeptinfo',
            name='dept_ch',
            field=models.CharField(max_length=255, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='branchorganizationinfo',
            name='organization',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='单位代号'),
        ),
        migrations.AlterField(
            model_name='headdeptinfo',
            name='dept',
            field=models.CharField(max_length=255, verbose_name='部门代号'),
        ),
        migrations.AlterField(
            model_name='headdeptinfo',
            name='dept_ch',
            field=models.CharField(max_length=255, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='headorganizationinfo',
            name='organization',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='单位代号'),
        ),
    ]
