# Generated by Django 2.0.4 on 2018-05-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headuserprofile',
            old_name='re_password',
            new_name='remedy_password',
        ),
        migrations.RenameField(
            model_name='headuserprofile',
            old_name='re_user_id',
            new_name='remedy_user_id',
        ),
    ]
