# Generated by Django 2.0.4 on 2018-05-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180515_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdeptinfo',
            name='organization',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='account.BranchOrganizationInfo', verbose_name='单位代号'),
        ),
        migrations.AlterField(
            model_name='branchuserprofile',
            name='dept',
            field=models.CharField(default='', max_length=255, verbose_name='部门代号'),
        ),
        migrations.AlterField(
            model_name='branchuserprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.BranchOrganizationInfo', verbose_name='单位代号'),
        ),
        migrations.AlterField(
            model_name='headdeptinfo',
            name='organization',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='account.HeadOrganizationInfo', verbose_name='单位代号'),
        ),
        migrations.AlterField(
            model_name='headuserprofile',
            name='dept',
            field=models.CharField(default='', max_length=255, verbose_name='团队代号'),
        ),
    ]
