# Generated by Django 2.0.4 on 2018-05-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskclosure',
            options={'verbose_name': '风险提示', 'verbose_name_plural': '风险提示'},
        ),
    ]
