# Generated by Django 2.0.4 on 2018-05-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmCheck',
            fields=[
                ('check_id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('s_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('r_time', models.DateTimeField(blank=True, null=True)),
                ('c_time', models.DateTimeField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=10, null=True)),
                ('describe', models.TextField(blank=True, max_length=3000, null=True)),
                ('influence', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, max_length=3000, null=True)),
                ('solution', models.IntegerField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, max_length=5000, null=True)),
                ('q_id', models.CharField(blank=True, max_length=32, null=True)),
                ('re_id', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.IntegerField(blank=True, null=True)),
                ('s_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('d_ip', models.TextField(blank=True, max_length=255, null=True)),
                ('s_address', models.CharField(blank=True, max_length=255, null=True)),
                ('d_address', models.CharField(blank=True, max_length=255, null=True)),
                ('stream', models.IntegerField(blank=True, null=True)),
                ('start_from', models.CharField(blank=True, max_length=255, null=True)),
                ('sustain', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '监控告警单',
                'verbose_name_plural': '监控告警单',
                'db_table': 'alarmCheck',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='EventCheck',
            fields=[
                ('check_id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('s_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('r_time', models.DateTimeField(blank=True, null=True)),
                ('c_time', models.DateTimeField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=10, null=True)),
                ('describe', models.TextField(blank=True, max_length=3000, null=True)),
                ('influence', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, max_length=3000, null=True)),
                ('solution', models.IntegerField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, max_length=5000, null=True)),
                ('title', models.TextField(blank=True, max_length=50, null=True)),
                ('history', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('a_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guard.AlarmCheck')),
            ],
            options={
                'db_table': 'eventCheck',
            },
        ),
    ]
