# Generated by Django 2.0.4 on 2018-05-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmCheck',
            fields=[
                ('check_id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='单号')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='标题')),
                ('status', models.CharField(choices=[('new', 'new'), ('process', 'process'), ('done', 'done'), ('close', 'close')], default='new', max_length=10, verbose_name='状态')),
                ('s_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('r_time', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('u_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('c_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='等级')),
                ('describe', models.TextField(blank=True, max_length=3000, null=True, verbose_name='描述')),
                ('influence', models.BooleanField(default=False, verbose_name='影响')),
                ('reason', models.TextField(blank=True, max_length=3000, null=True, verbose_name='原因')),
                ('solution', models.IntegerField(blank=True, null=True, verbose_name='解决方式')),
                ('plan', models.TextField(blank=True, max_length=5000, null=True, verbose_name='解决方案')),
                ('q_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Qradar单号')),
                ('re_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remedy单号')),
                ('classification', models.IntegerField(blank=True, null=True, verbose_name='攻击类型')),
                ('s_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='源IP')),
                ('d_ip', models.TextField(blank=True, max_length=255, null=True, verbose_name='源目的IP')),
                ('s_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='源地址')),
                ('d_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='目的地址')),
                ('stream', models.IntegerField(blank=True, null=True, verbose_name='流数目')),
                ('start_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='开始时间')),
                ('sustain', models.CharField(blank=True, max_length=255, null=True, verbose_name='持续时间')),
                ('app', models.CharField(blank=True, max_length=255, null=True, verbose_name='攻击应用')),
                ('r_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.HeadUser', verbose_name='受理人工号')),
            ],
            options={
                'verbose_name': '监控告警单',
                'verbose_name_plural': '监控告警单',
                'db_table': 'AlarmCheck',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='单号')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('candidate', models.ManyToManyField(related_name='candidate', to='account.HeadUser', verbose_name='被评人')),
                ('judge', models.ManyToManyField(related_name='judge', to='account.HeadUser', verbose_name='评价人')),
            ],
            options={
                'verbose_name': '员工评价单',
                'verbose_name_plural': '员工评价单',
                'db_table': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='EventCheck',
            fields=[
                ('check_id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='单号')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='标题')),
                ('status', models.CharField(choices=[('new', 'new'), ('process', 'process'), ('done', 'done'), ('close', 'close')], default='new', max_length=10, verbose_name='状态')),
                ('s_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('r_time', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('u_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('c_time', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('rank', models.CharField(blank=True, max_length=10, null=True, verbose_name='等级')),
                ('describe', models.TextField(blank=True, max_length=3000, null=True, verbose_name='描述')),
                ('influence', models.BooleanField(default=False, verbose_name='影响')),
                ('reason', models.TextField(blank=True, max_length=3000, null=True, verbose_name='原因')),
                ('solution', models.IntegerField(blank=True, null=True, verbose_name='解决方式')),
                ('plan', models.TextField(blank=True, max_length=5000, null=True, verbose_name='解决方案')),
                ('history', models.CharField(blank=True, max_length=255, null=True, verbose_name='历史记录')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='附件')),
                ('a_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_id', to='guard.AlarmCheck', verbose_name='关联告警单号')),
                ('r_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_id', to='account.HeadUser', verbose_name='受理人工号')),
                ('s_id', models.ManyToManyField(blank=True, null=True, related_name='s_id', to='account.HeadUser', verbose_name='建单人工号')),
                ('transmit', models.ManyToManyField(blank=True, null=True, related_name='transmit', to='account.HeadUser', verbose_name='转派工号')),
            ],
            options={
                'verbose_name': '威胁事件单',
                'verbose_name_plural': '威胁事件单',
                'db_table': 'EventCheck',
            },
        ),
    ]
