# Generated by Django 2.0.4 on 2018-05-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcheck',
            name='s_id',
            field=models.ManyToManyField(related_name='s_id', to='userauth.HeadUser'),
        ),
        migrations.AddField(
            model_name='eventcheck',
            name='transmit',
            field=models.ManyToManyField(related_name='transmit', to='userauth.HeadUser'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='candidate',
            field=models.ManyToManyField(related_name='candidate', to='userauth.HeadUser'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='judge',
            field=models.ManyToManyField(related_name='judge', to='userauth.HeadUser'),
        ),
        migrations.AddField(
            model_name='alarmcheck',
            name='r_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.HeadUser'),
        ),
    ]
