# Generated by Django 2.0.4 on 2018-05-08 06:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardPlan',
            fields=[
                ('time', models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='值班日期')),
                ('product_judge', models.FloatField(default=0, verbose_name='一线值班进度')),
                ('second_judge', models.FloatField(default=100, verbose_name='二线值班进度')),
                ('third_judge', models.FloatField(default=100, verbose_name='三线值班进度')),
                ('report', models.FilePathField(blank=True, max_length=255, null=True, verbose_name='日报')),
                ('product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='account.HeadUser', verbose_name='一线值班员')),
                ('second_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='account.HeadUser', verbose_name='二线值班员')),
                ('third_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='account.HeadUser', verbose_name='三线值班员')),
            ],
            options={
                'verbose_name': '值班安排表',
                'verbose_name_plural': '值班安排表',
                'db_table': 'GuardPlan',
            },
        ),
        migrations.RemoveField(
            model_name='eventcheck',
            name='solution',
        ),
        migrations.AlterField(
            model_name='alarmcheck',
            name='rank',
            field=models.CharField(choices=[('1', '一级安全事件'), ('2', '二级安全事件'), ('3', '三级安全事件')], default='3', max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='alarmcheck',
            name='solution',
            field=models.IntegerField(choices=[('1', '继续观察'), ('2', '提交阻断服务请求'), ('3', '其他处理方式')], default='1', verbose_name='解决方式'),
        ),
        migrations.AlterField(
            model_name='alarmcheck',
            name='status',
            field=models.CharField(choices=[('new', '新建'), ('process', '处理中'), ('done', '完成'), ('close', '关闭')], default='new', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='rank',
            field=models.CharField(choices=[('1', '一级安全事件'), ('2', '二级安全事件'), ('3', '三级安全事件')], default='3', max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='eventcheck',
            name='status',
            field=models.CharField(choices=[('new', '新建'), ('process', '处理中'), ('done', '完成'), ('close', '关闭')], default='new', max_length=10, verbose_name='状态'),
        ),
    ]
