# Generated by Django 2.0.4 on 2018-05-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_auto_20180508_1433'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alarmcheck',
            table='alarm_check',
        ),
        migrations.AlterModelTable(
            name='evaluation',
            table='evaluation',
        ),
        migrations.AlterModelTable(
            name='eventcheck',
            table='event_check',
        ),
        migrations.AlterModelTable(
            name='guardplan',
            table='guard_plan',
        ),
    ]
