# Generated by Django 2.0.4 on 2018-05-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180508_1604'),
        ('guard', '0003_auto_20180508_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcheck',
            name='s_id',
        ),
        migrations.AddField(
            model_name='eventcheck',
            name='s_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_id', to='account.HeadUser', verbose_name='建单人工号'),
        ),
        migrations.RemoveField(
            model_name='eventcheck',
            name='transmit',
        ),
        migrations.AddField(
            model_name='eventcheck',
            name='transmit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmit', to='account.HeadUser', verbose_name='转派工号'),
        ),
    ]
