# Generated by Django 2.0.4 on 2018-05-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlowField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField(verbose_name='工作流id')),
                ('field_type_id', models.IntegerField(help_text='见service.constant_service中定义', verbose_name='类型')),
                ('field_key', models.CharField(max_length=50, verbose_name='字段标识')),
                ('field_name', models.CharField(max_length=50, verbose_name='字段名称')),
                ('order_id', models.IntegerField(default=0, verbose_name='排序')),
                ('default_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='默认值')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='描述')),
                ('field_template', models.TextField(blank=True, default='', help_text='文本域字段支持配置内容模板', verbose_name='模板')),
                ('boolean_field_display', models.CharField(blank=True, help_text='当为布尔类型时候，可以支持自定义显示形式。{1:"是",0:"否"}或{1:"需要",0:"不需要"}', max_length=100, null=True, verbose_name='布尔类型显示名')),
                ('field_choice', models.CharField(blank=True, default='[]', help_text='radio,checkbox,select,multiselect类型可供选择的选项，格式为json如:{1:"中国",2:"美国"}', max_length=1000, verbose_name='radio选项')),
                ('create_user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工作流自定义字段',
                'verbose_name_plural': '工作流自定义字段',
                'db_table': 'custom_flow_field',
            },
        ),
        migrations.CreateModel(
            name='CustomFlowNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('script', models.FileField(blank=True, null=True, upload_to='notice_script', verbose_name='通知脚本')),
                ('title_template', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题模板')),
                ('content_template', models.CharField(blank=True, max_length=1000, null=True, verbose_name='内容模板')),
                ('create_user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '自定义通知脚本',
                'verbose_name_plural': '自定义通知脚本',
                'db_table': 'custom_flow_notice',
            },
        ),
        migrations.CreateModel(
            name='FlowState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('workflow_id', models.IntegerField(verbose_name='工作流')),
                ('sub_workflow_id', models.IntegerField(blank=True, default=0, verbose_name='子工作流id(如果需要在此状态启用子工单的话)')),
                ('is_hidden', models.BooleanField(default=0, help_text='设置为True时,工单步骤中不显示此状态(当前处于此状态时除外)', verbose_name='是否隐藏')),
                ('order_id', models.IntegerField(default=0, help_text='用于工单步骤接口时，step上状态的顺序(因为存在网状情况，所以需要认为设定顺序),值越小越靠前', verbose_name='状态顺序')),
                ('type_id', models.IntegerField(default=0, help_text='见service.constant_service中定义', verbose_name='状态类型id')),
                ('participant_type_id', models.IntegerField(blank=True, default=1, help_text='见service.constant_service中定义', verbose_name='参与者类型id')),
                ('participant', models.CharField(blank=True, default='', help_text='可以为username\\多个username(以,隔开)\\部门id\\角色id\\变量id等', max_length=100, verbose_name='参与者')),
                ('distribute_type_id', models.IntegerField(default=1, help_text='见service.constant_service中定义', verbose_name='分配方式')),
                ('state_field_str', models.TextField(default='{}', help_text='json格式字典存储,包括读写属性1：只读，2：必填，3：可选. 示例：{"created_at":1,"title":2, "sn":1}', verbose_name='表单字段')),
                ('label', models.CharField(default='{}', help_text='json格式，由调用方根据实际定制需求自行确定,如状态下需要显示哪些前端组件:{"components":[{"AppList":1, "ProjectList":7}]}', max_length=1000, verbose_name='状态标签')),
                ('create_user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工作流状态',
                'verbose_name_plural': '工作流状态',
                'db_table': 'flow_state',
            },
        ),
        migrations.CreateModel(
            name='FlowTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='操作')),
                ('workflow_id', models.IntegerField(verbose_name='工作流id')),
                ('transition_type_id', models.IntegerField(default=1, help_text='见service.constant_service中定义', verbose_name='流转类型')),
                ('source_state_id', models.IntegerField(verbose_name='源状态id')),
                ('destination_state_id', models.IntegerField(verbose_name='目的状态id')),
                ('field_require_check', models.BooleanField(default=True, help_text='默认在用户点击操作的时候需要校验工单表单的必填项,如果设置为否则不检查。用于如"退回"属性的操作，不需要填写表单内容', verbose_name='是否校验必填项')),
                ('alert_enable', models.BooleanField(default=False, verbose_name='点击弹窗提示')),
                ('alert_text', models.CharField(blank=True, default='', max_length=100, verbose_name='弹窗内容')),
                ('create_user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工作流流转',
                'verbose_name_plural': '工作流流转',
                'db_table': 'flow_transition',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='流程号')),
                ('workflow_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='描述')),
                ('flow_chart', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='流程图路径')),
                ('notice_type', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='通知方式')),
                ('permission_check', models.BooleanField(default=1, help_text='只允许工单的关联人查看工单', verbose_name='权限校验')),
                ('limit_expression', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='限制表达式')),
                ('form_desplay', models.CharField(blank=True, default='[]', help_text='json格式，用于用户只有查看权限时显示哪些字段,field_key的list', max_length=10000, null=True, verbose_name='展现表单字段')),
                ('default_notice_to', models.CharField(blank=True, default='', help_text='表单创建及结束时会发送相应通知信息', max_length=50, null=True, verbose_name='默认通知人')),
                ('create_user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流',
                'db_table': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='WorkflowScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('saved_name', models.CharField(max_length=50, verbose_name='存储的文件名')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='可用')),
                ('create_user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
            ],
            options={
                'verbose_name': '工作流脚本',
                'verbose_name_plural': '工作流脚本',
                'db_table': 'work_flow_script',
            },
        ),
    ]
